version: '3.3'
   
services:
  tum:
    image: tum:0.1b
    container_name: tum
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - '8001:8000'
    environment:
      # [TUM] Settings
      - DEBUG=on
      - ALLOWED_HOSTS=127.0.0.1,localhost
      - SECRET_KEY=
      # [TikTok] Cookies
      - tt_csrf_token=
      - _abck=
      - ak_bmsc=
      - bm_sz=
      - passport_csrf_token=
      - passport_csrf_token_default=
      - bm_mi=
      - ttwid=
      - msToken=
      - cmpl_token=
      - store_idc=
      - store_country_code=
      - tt_target_idc=
      - bm_sv=
      - odin_tt=
      - sid_guard=
      - uid_tt=
      - uid_tt_ss=
      - sid_tt=
      - sessionid=
      - sessionid_ss=
      - sid_ucp_v1=
      - ssid_ucp_v1=
      # [TikTok] Headers
      - sec_ch_ua=
      - sec_ch_ua_mobile=
      - sec_fetch_dest=
      - sec_fetch_mode=
      - sec_fetch_site=
      - user_agent=
